//
// Created by Ivan Rodriguez on 9/23/20.
//

enum Tag{
    CLASS = 1, ELSE, FALSE, FI, IF, IN, INHERITS, ISVOID, LET, LOOP, POOL, THEN, WHILE, CASE, ESAC, NEW, OF, NOT, TRUE,
    INTEGER, TYPEID, OBJECTID, COLON, SEMICOLON, LPAREN, RPAREN, LBRACKET, RBRACKET, LCURLY, RCURLY, ASSIGNMENT, DOT,
    COMMA, AT, PLUS, MINUS, TIMES, DIVIDE, TILDA, LT, LTE, EQ, STRING
};